repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^tvbingefriend_show_service/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        files: ^tvbingefriend_show_service/
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    -   id: bandit
        args: [-r]
        files: ^tvbingefriend_show_service/
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: bash -c 'SQLALCHEMY_CONNECTION_STRING="sqlite:///:memory:" pytest tests/'
        language: system
        types: [python]
        pass_filenames: false
