repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: poetry run ruff check --fix tvbingefriend_show_service/
        language: system
        types: [python]
        pass_filenames: false
    -   id: mypy
        name: mypy
        entry: poetry run mypy tvbingefriend_show_service/
        language: system
        types: [python]
        pass_filenames: false
    -   id: bandit
        name: bandit
        entry: poetry run bandit -r tvbingefriend_show_service/
        language: system
        types: [python]
        pass_filenames: false
    -   id: pytest
        name: pytest
        entry: bash -c 'poetry run pytest tests/'
        language: system
        types: [python]
        pass_filenames: false
