"""initial schema

Revision ID: 3777d1089697
Revises: d507649d3bde
Create Date: 2025-08-17 17:18:47.028629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3777d1089697'
down_revision: Union[str, Sequence[str], None] = 'd507649d3bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('genres', mysql.JSON(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('runtime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('averageRuntime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('premiered', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ended', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('officialSite', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('schedule', mysql.JSON(), nullable=True),
    sa.Column('rating', mysql.JSON(), nullable=True),
    sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('network', mysql.JSON(), nullable=True),
    sa.Column('webchannel', mysql.JSON(), nullable=True),
    sa.Column('dvdCountry', mysql.JSON(), nullable=True),
    sa.Column('externals', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', mysql.TEXT(), nullable=True),
    sa.Column('updated', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
