"""initial schema

Revision ID: d560e5935f26
Revises: 
Create Date: 2025-08-23 20:29:18.911526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd560e5935f26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('genres', mysql.JSON(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('averageRuntime', sa.Integer(), nullable=True),
    sa.Column('premiered', sa.String(length=255), nullable=True),
    sa.Column('ended', sa.String(length=255), nullable=True),
    sa.Column('officialSite', sa.String(length=255), nullable=True),
    sa.Column('schedule', mysql.JSON(), nullable=True),
    sa.Column('rating', mysql.JSON(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('network', mysql.JSON(), nullable=True),
    sa.Column('webchannel', mysql.JSON(), nullable=True),
    sa.Column('dvdCountry', mysql.JSON(), nullable=True),
    sa.Column('externals', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
